koopjs/koop-agol

controller/index.js, models/agol.js
Needed to return 202 and kick off caching whenever a geohash is requested on a layer that is not cached
=> Geohash processing

CHANGELOG.md, controller/index.js
Removes dollar signs in file names, causing trouble in exporting.
=> Dollar signs files

CHANGELOG.md, models/agol.js, workers/request-worker.js
This PR fixes a few things I've seen hurting workers in production and on qa. Overall its gracefully exiting when jobs fail.
=> Worker fixes

CHANGELOG.md, models/agol.js, workers/request-worker.js, workers/worker-log.log
A few nice things for workers that will help keep the queues free of stuck jobs
=> Worker backoffs

CHANGELOG.md, controller/index.js, package.json
The workers rely on yargs and it wasnt added to the package on the last PR
=> Adds yargs

CHANGELOG.md, controller/index.js, package.json
ping @ngoldman or @jgravois 
Pretty sure this is the last change before we can release this version of Koop-AGOL
=> ensure naming consistency

CHANGELOG.md, controller/index.js, models/agol.js
just a little cleanup to reduce unnecessary http calls and avoid bombing out on bad keys
=> tweak expiration flow

.gitignore, controller/index.js, test/controller-test.js
Nothing to add to the change logs since this there are no external changes vs the last release
=> fix naming and creation of geohashes

controller/index.js, models/agol.js, test/model-test.js, workers/request-worker.js
@ngoldman this is meant to work in sync with the featureservice PR
=> standardize errors for feature service chain

CHANGELOG.md, models/agol.js
ping @ngoldman 
I'm disappointed I missed this but it needs to be released right away because 1.1.1 is broken.
=> fix error catching

CHANGELOG.md, controller/index.js, index.js, models/agol.js, package.json, routes/index.js, test/controller-test.js, test/model-test.js, views/demo.ejs, workers/request-worker.js
just some reformatting to pass standard 5+ and a couple readability improvements
=> bump to standard 5

CHANGELOG.md, controller/index.js, lib/utils.js, models/agol.js, package.json, routes/index.js, test/controller-test.js, test/utils-test.js
ping @AKHarris 
This PR straightens out some errors with routing to Feature Server without a layer as well as cache keys for all requests. I definitely need to remove the setHostKey route and call those functions from other places but that is out of scope for this PR.
=> Misc fixes

.gitignore, CHANGELOG.md, controller/index.js, models/agol.js, package.json, test/controller-test.js, test/model-test.js, workers/request-worker.js
This PR adds logging throughout the download request cycle and a few other methods. It also changes style for logging to `log.level(message)` instead of `log.(level, message)`.
cc @koopjs/dev @jwieringa
=> log all the things!

CHANGELOG.md, models/agol.js
=> pass central logger to featureservice

lib/cache.js, lib/import-service.js, package.json
Add indexes after data is inserted, requires pg-cache v >1.5.x
=> add indexes after data is fully inserted

CHANGELOG.md, lib/cache.js, lib/csv-request.js, lib/import-service.js, package.json
Cache, csv-request, and import service converted over to esri-to-geojson
=> Integrate esri to geojson

controller/index.js, lib/cache.js, models/agol.js, test/controller-test.js, test/model-test.js
Entirely sure that the changes to make the tests pass are incorrect. Let's start with the model-test.js as if that is incorrect it can help inform for the others.
=> Reduce latency

CHANGELOG.md, controller/index.js, lib/cache.js, package.json
@dmfenton Ended up being on the same branch as yesterday.
=> Esri to geojson 1.0.2

CHANGELOG.md
fix for the problem also seen in the **3.6.4** release notes
```
Better error handling for csv errors ### Changed
```
=> add a new line before hashed section

CHANGELOG.md, lib/utils.js, test/utils-test.js
@dmfenton I don't know why I didn't make a pr on this........
=> createExportOptions now takes fields array
